---
swagger: "2.0"
info:
  version: "1.0.0-SNAPSHOT"
  title: "Startup Service"
host: "startup.com"
basePath: "/v1"
tags:
- name: "Startup"
schemes:
- "https"
paths:
  /startup/users:
    get:
      tags:
      - "Startup"
      summary: "Returns all users along with info"
      description: ""
      operationId: "getUsers"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Users returned successfully"
          schema:
            $ref: "#/definitions/UserDto"
        400:
          description: "The request was invalid."
        500:
          description: "An internal server error occurred."
  /startup/users/{id}:
    get:
      tags:
      - "Startup"
      summary: "Returns info of the given user"
      description: ""
      operationId: "getUser"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "User info successfully returned"
          schema:
            $ref: "#/definitions/UserDto"
        400:
          description: "The request was invalid."
        500:
          description: "An internal server error occurred."
definitions:
  UserDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      email:
        type: "string"
