---
swagger: "2.0"
info:
  version: "1.0.0-SNAPSHOT"
  title: "Startup Service"
host: "startup.com"
basePath: "/v1"
tags:
- name: "Game"
schemes:
- "https"
paths:
  /game:
    post:
      tags:
      - "Game"
      summary: "Creates a game"
      description: ""
      operationId: "createGame"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Game created successfully"
          schema:
            $ref: "#/definitions/GameDto"
        400:
          description: "The request was invalid."
        500:
          description: "An internal server error occurred."
definitions:
  GameDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      guid:
        type: "string"
      code:
        type: "string"
      type:
        type: "string"
        enum:
        - "TEXAS_HOLDEM"
        - "CRAZY_PINEAPPLE"
      startDate:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"
      winsRequired:
        type: "integer"
        format: "int32"
